name: Test Container

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker Container Image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: false
        tags: shtl-ink-api
    - name: Test Container Image
      run: |
        docker run --entrypoint pytest --rm -it shtl-ink-api:latest shtl_ink/tests